dataset:
  data_folder: /Users/anhv/.underthesea/datasets/VLSP2013-WTK-R2/
  train_file: train.txt
  dev_file: dev.txt
  test_file: test.txt
  downsample: 0.01
trainer:
  max_iterations: 10
model:
  c1: 1.0
  c2: 1e-3
  features:
    - T[-2]::T[-1]::T[0]::T[1]::T[2]
    - T[-2,-1]::T[-1,0]::T[0,1]::T[1,2]
    - T[-2,0]::T[-1,1]::T[0,2]
    - T[-2].lower::T[-1].lower::T[0].lower::T[1].lower::T[2].lower
    - T[-2,-1].lower::T[-1,0].lower::T[0,1].lower::T[1,2].lower
    - T[-1].isdigit::T[0].isdigit::T[1].isdigit
    - T[-2].istitle::T[-1].istitle::T[0].istitle::T[1].istitle::T[2].istitle
    - T[0,1].istitle::T[0,2].istitle
    - T[-2].is_in_dict::T[-1].is_in_dict::T[0].is_in_dict::T[1].is_in_dict::T[2].is_in_dict
    - T[-2,-1].is_in_dict::T[-1,0].is_in_dict::T[0,1].is_in_dict::T[1,2].is_in_dict
    - T[-2,0].is_in_dict::T[-1,1].is_in_dict::T[0,2].is_in_dict
base_path: models/wtk_crf_2